//
// Copyright (c) ZeroC, Inc. All rights reserved.
//
//
// Ice version 3.7.10
//
// <auto-generated>
//
// Generated from file `chat.ice'
//
// Warning: do not edit this file.
//
// </auto-generated>
//

package chat;

public class AudioInfo implements java.lang.Cloneable,
                                  java.io.Serializable
{
    public String id;

    public String from;

    public String to;

    public long timestamp;

    public boolean isGroup;

    public int duration;

    public int size;

    public AudioInfo()
    {
        this.id = "";
        this.from = "";
        this.to = "";
    }

    public AudioInfo(String id, String from, String to, long timestamp, boolean isGroup, int duration, int size)
    {
        this.id = id;
        this.from = from;
        this.to = to;
        this.timestamp = timestamp;
        this.isGroup = isGroup;
        this.duration = duration;
        this.size = size;
    }

    public boolean equals(java.lang.Object rhs)
    {
        if(this == rhs)
        {
            return true;
        }
        AudioInfo r = null;
        if(rhs instanceof AudioInfo)
        {
            r = (AudioInfo)rhs;
        }

        if(r != null)
        {
            if(this.id != r.id)
            {
                if(this.id == null || r.id == null || !this.id.equals(r.id))
                {
                    return false;
                }
            }
            if(this.from != r.from)
            {
                if(this.from == null || r.from == null || !this.from.equals(r.from))
                {
                    return false;
                }
            }
            if(this.to != r.to)
            {
                if(this.to == null || r.to == null || !this.to.equals(r.to))
                {
                    return false;
                }
            }
            if(this.timestamp != r.timestamp)
            {
                return false;
            }
            if(this.isGroup != r.isGroup)
            {
                return false;
            }
            if(this.duration != r.duration)
            {
                return false;
            }
            if(this.size != r.size)
            {
                return false;
            }

            return true;
        }

        return false;
    }

    public int hashCode()
    {
        int h_ = 5381;
        h_ = com.zeroc.IceInternal.HashUtil.hashAdd(h_, "::chat::AudioInfo");
        h_ = com.zeroc.IceInternal.HashUtil.hashAdd(h_, id);
        h_ = com.zeroc.IceInternal.HashUtil.hashAdd(h_, from);
        h_ = com.zeroc.IceInternal.HashUtil.hashAdd(h_, to);
        h_ = com.zeroc.IceInternal.HashUtil.hashAdd(h_, timestamp);
        h_ = com.zeroc.IceInternal.HashUtil.hashAdd(h_, isGroup);
        h_ = com.zeroc.IceInternal.HashUtil.hashAdd(h_, duration);
        h_ = com.zeroc.IceInternal.HashUtil.hashAdd(h_, size);
        return h_;
    }

    public AudioInfo clone()
    {
        AudioInfo c = null;
        try
        {
            c = (AudioInfo)super.clone();
        }
        catch(CloneNotSupportedException ex)
        {
            assert false; // impossible
        }
        return c;
    }

    public void ice_writeMembers(com.zeroc.Ice.OutputStream ostr)
    {
        ostr.writeString(this.id);
        ostr.writeString(this.from);
        ostr.writeString(this.to);
        ostr.writeLong(this.timestamp);
        ostr.writeBool(this.isGroup);
        ostr.writeInt(this.duration);
        ostr.writeInt(this.size);
    }

    public void ice_readMembers(com.zeroc.Ice.InputStream istr)
    {
        this.id = istr.readString();
        this.from = istr.readString();
        this.to = istr.readString();
        this.timestamp = istr.readLong();
        this.isGroup = istr.readBool();
        this.duration = istr.readInt();
        this.size = istr.readInt();
    }

    static public void ice_write(com.zeroc.Ice.OutputStream ostr, AudioInfo v)
    {
        if(v == null)
        {
            _nullMarshalValue.ice_writeMembers(ostr);
        }
        else
        {
            v.ice_writeMembers(ostr);
        }
    }

    static public AudioInfo ice_read(com.zeroc.Ice.InputStream istr)
    {
        AudioInfo v = new AudioInfo();
        v.ice_readMembers(istr);
        return v;
    }

    static public void ice_write(com.zeroc.Ice.OutputStream ostr, int tag, java.util.Optional<AudioInfo> v)
    {
        if(v != null && v.isPresent())
        {
            ice_write(ostr, tag, v.get());
        }
    }

    static public void ice_write(com.zeroc.Ice.OutputStream ostr, int tag, AudioInfo v)
    {
        if(ostr.writeOptional(tag, com.zeroc.Ice.OptionalFormat.FSize))
        {
            int pos = ostr.startSize();
            ice_write(ostr, v);
            ostr.endSize(pos);
        }
    }

    static public java.util.Optional<AudioInfo> ice_read(com.zeroc.Ice.InputStream istr, int tag)
    {
        if(istr.readOptional(tag, com.zeroc.Ice.OptionalFormat.FSize))
        {
            istr.skip(4);
            return java.util.Optional.of(AudioInfo.ice_read(istr));
        }
        else
        {
            return java.util.Optional.empty();
        }
    }

    private static final AudioInfo _nullMarshalValue = new AudioInfo();

    /** @hidden */
    public static final long serialVersionUID = 1928550202L;
}
