//
// Copyright (c) ZeroC, Inc. All rights reserved.
//
//
// Ice version 3.7.10
//
// <auto-generated>
//
// Generated from file `chat.ice'
//
// Warning: do not edit this file.
//
// </auto-generated>
//

package chat;

/**
 * Helper class for marshaling/unmarshaling AudioSeq.
 **/
public final class AudioSeqHelper
{
    public static void write(com.zeroc.Ice.OutputStream ostr, AudioInfo[] v)
    {
        if(v == null)
        {
            ostr.writeSize(0);
        }
        else
        {
            ostr.writeSize(v.length);
            for(int i0 = 0; i0 < v.length; i0++)
            {
                AudioInfo.ice_write(ostr, v[i0]);
            }
        }
    }

    public static AudioInfo[] read(com.zeroc.Ice.InputStream istr)
    {
        final AudioInfo[] v;
        final int len0 = istr.readAndCheckSeqSize(20);
        v = new AudioInfo[len0];
        for(int i0 = 0; i0 < len0; i0++)
        {
            v[i0] = AudioInfo.ice_read(istr);
        }
        return v;
    }

    public static void write(com.zeroc.Ice.OutputStream ostr, int tag, java.util.Optional<AudioInfo[]> v)
    {
        if(v != null && v.isPresent())
        {
            write(ostr, tag, v.get());
        }
    }

    public static void write(com.zeroc.Ice.OutputStream ostr, int tag, AudioInfo[] v)
    {
        if(ostr.writeOptional(tag, com.zeroc.Ice.OptionalFormat.FSize))
        {
            int pos = ostr.startSize();
            AudioSeqHelper.write(ostr, v);
            ostr.endSize(pos);
        }
    }

    public static java.util.Optional<AudioInfo[]> read(com.zeroc.Ice.InputStream istr, int tag)
    {
        if(istr.readOptional(tag, com.zeroc.Ice.OptionalFormat.FSize))
        {
            istr.skip(4);
            AudioInfo[] v;
            v = AudioSeqHelper.read(istr);
            return java.util.Optional.of(v);
        }
        else
        {
            return java.util.Optional.empty();
        }
    }
}
