//
// Copyright (c) ZeroC, Inc. All rights reserved.
//
//
// Ice version 3.7.10
//
// <auto-generated>
//
// Generated from file `chat.ice'
//
// Warning: do not edit this file.
//
// </auto-generated>
//

package chat;

public interface ChatServicePrx extends com.zeroc.Ice.ObjectPrx
{
    default boolean login(String username)
        throws UserException
    {
        return login(username, com.zeroc.Ice.ObjectPrx.noExplicitContext);
    }

    default boolean login(String username, java.util.Map<String, String> context)
        throws UserException
    {
        try
        {
            return _iceI_loginAsync(username, context, true).waitForResponseOrUserEx();
        }
        catch(UserException ex)
        {
            throw ex;
        }
        catch(com.zeroc.Ice.UserException ex)
        {
            throw new com.zeroc.Ice.UnknownUserException(ex.ice_id(), ex);
        }
    }

    default java.util.concurrent.CompletableFuture<java.lang.Boolean> loginAsync(String username)
    {
        return _iceI_loginAsync(username, com.zeroc.Ice.ObjectPrx.noExplicitContext, false);
    }

    default java.util.concurrent.CompletableFuture<java.lang.Boolean> loginAsync(String username, java.util.Map<String, String> context)
    {
        return _iceI_loginAsync(username, context, false);
    }

    /**
     * @hidden
     * @param iceP_username -
     * @param context -
     * @param sync -
     * @return -
     **/
    default com.zeroc.IceInternal.OutgoingAsync<java.lang.Boolean> _iceI_loginAsync(String iceP_username, java.util.Map<String, String> context, boolean sync)
    {
        com.zeroc.IceInternal.OutgoingAsync<java.lang.Boolean> f = new com.zeroc.IceInternal.OutgoingAsync<>(this, "login", null, sync, _iceE_login);
        f.invoke(true, context, null, ostr -> {
                     ostr.writeString(iceP_username);
                 }, istr -> {
                     boolean ret;
                     ret = istr.readBool();
                     return ret;
                 });
        return f;
    }

    /** @hidden */
    static final Class<?>[] _iceE_login =
    {
        UserException.class
    };

    default boolean logout(String username)
        throws UserException
    {
        return logout(username, com.zeroc.Ice.ObjectPrx.noExplicitContext);
    }

    default boolean logout(String username, java.util.Map<String, String> context)
        throws UserException
    {
        try
        {
            return _iceI_logoutAsync(username, context, true).waitForResponseOrUserEx();
        }
        catch(UserException ex)
        {
            throw ex;
        }
        catch(com.zeroc.Ice.UserException ex)
        {
            throw new com.zeroc.Ice.UnknownUserException(ex.ice_id(), ex);
        }
    }

    default java.util.concurrent.CompletableFuture<java.lang.Boolean> logoutAsync(String username)
    {
        return _iceI_logoutAsync(username, com.zeroc.Ice.ObjectPrx.noExplicitContext, false);
    }

    default java.util.concurrent.CompletableFuture<java.lang.Boolean> logoutAsync(String username, java.util.Map<String, String> context)
    {
        return _iceI_logoutAsync(username, context, false);
    }

    /**
     * @hidden
     * @param iceP_username -
     * @param context -
     * @param sync -
     * @return -
     **/
    default com.zeroc.IceInternal.OutgoingAsync<java.lang.Boolean> _iceI_logoutAsync(String iceP_username, java.util.Map<String, String> context, boolean sync)
    {
        com.zeroc.IceInternal.OutgoingAsync<java.lang.Boolean> f = new com.zeroc.IceInternal.OutgoingAsync<>(this, "logout", null, sync, _iceE_logout);
        f.invoke(true, context, null, ostr -> {
                     ostr.writeString(iceP_username);
                 }, istr -> {
                     boolean ret;
                     ret = istr.readBool();
                     return ret;
                 });
        return f;
    }

    /** @hidden */
    static final Class<?>[] _iceE_logout =
    {
        UserException.class
    };

    default boolean sendMessage(String from, String to, String content)
        throws UserException
    {
        return sendMessage(from, to, content, com.zeroc.Ice.ObjectPrx.noExplicitContext);
    }

    default boolean sendMessage(String from, String to, String content, java.util.Map<String, String> context)
        throws UserException
    {
        try
        {
            return _iceI_sendMessageAsync(from, to, content, context, true).waitForResponseOrUserEx();
        }
        catch(UserException ex)
        {
            throw ex;
        }
        catch(com.zeroc.Ice.UserException ex)
        {
            throw new com.zeroc.Ice.UnknownUserException(ex.ice_id(), ex);
        }
    }

    default java.util.concurrent.CompletableFuture<java.lang.Boolean> sendMessageAsync(String from, String to, String content)
    {
        return _iceI_sendMessageAsync(from, to, content, com.zeroc.Ice.ObjectPrx.noExplicitContext, false);
    }

    default java.util.concurrent.CompletableFuture<java.lang.Boolean> sendMessageAsync(String from, String to, String content, java.util.Map<String, String> context)
    {
        return _iceI_sendMessageAsync(from, to, content, context, false);
    }

    /**
     * @hidden
     * @param iceP_from -
     * @param iceP_to -
     * @param iceP_content -
     * @param context -
     * @param sync -
     * @return -
     **/
    default com.zeroc.IceInternal.OutgoingAsync<java.lang.Boolean> _iceI_sendMessageAsync(String iceP_from, String iceP_to, String iceP_content, java.util.Map<String, String> context, boolean sync)
    {
        com.zeroc.IceInternal.OutgoingAsync<java.lang.Boolean> f = new com.zeroc.IceInternal.OutgoingAsync<>(this, "sendMessage", null, sync, _iceE_sendMessage);
        f.invoke(true, context, null, ostr -> {
                     ostr.writeString(iceP_from);
                     ostr.writeString(iceP_to);
                     ostr.writeString(iceP_content);
                 }, istr -> {
                     boolean ret;
                     ret = istr.readBool();
                     return ret;
                 });
        return f;
    }

    /** @hidden */
    static final Class<?>[] _iceE_sendMessage =
    {
        UserException.class
    };

    default MessageInfo[] getPrivateHistory(String username, String target)
        throws UserException
    {
        return getPrivateHistory(username, target, com.zeroc.Ice.ObjectPrx.noExplicitContext);
    }

    default MessageInfo[] getPrivateHistory(String username, String target, java.util.Map<String, String> context)
        throws UserException
    {
        try
        {
            return _iceI_getPrivateHistoryAsync(username, target, context, true).waitForResponseOrUserEx();
        }
        catch(UserException ex)
        {
            throw ex;
        }
        catch(com.zeroc.Ice.UserException ex)
        {
            throw new com.zeroc.Ice.UnknownUserException(ex.ice_id(), ex);
        }
    }

    default java.util.concurrent.CompletableFuture<MessageInfo[]> getPrivateHistoryAsync(String username, String target)
    {
        return _iceI_getPrivateHistoryAsync(username, target, com.zeroc.Ice.ObjectPrx.noExplicitContext, false);
    }

    default java.util.concurrent.CompletableFuture<MessageInfo[]> getPrivateHistoryAsync(String username, String target, java.util.Map<String, String> context)
    {
        return _iceI_getPrivateHistoryAsync(username, target, context, false);
    }

    /**
     * @hidden
     * @param iceP_username -
     * @param iceP_target -
     * @param context -
     * @param sync -
     * @return -
     **/
    default com.zeroc.IceInternal.OutgoingAsync<MessageInfo[]> _iceI_getPrivateHistoryAsync(String iceP_username, String iceP_target, java.util.Map<String, String> context, boolean sync)
    {
        com.zeroc.IceInternal.OutgoingAsync<MessageInfo[]> f = new com.zeroc.IceInternal.OutgoingAsync<>(this, "getPrivateHistory", null, sync, _iceE_getPrivateHistory);
        f.invoke(true, context, null, ostr -> {
                     ostr.writeString(iceP_username);
                     ostr.writeString(iceP_target);
                 }, istr -> {
                     MessageInfo[] ret;
                     ret = MessageSeqHelper.read(istr);
                     return ret;
                 });
        return f;
    }

    /** @hidden */
    static final Class<?>[] _iceE_getPrivateHistory =
    {
        UserException.class
    };

    default boolean sendGroupMessage(String from, String groupName, String content)
        throws UserException
    {
        return sendGroupMessage(from, groupName, content, com.zeroc.Ice.ObjectPrx.noExplicitContext);
    }

    default boolean sendGroupMessage(String from, String groupName, String content, java.util.Map<String, String> context)
        throws UserException
    {
        try
        {
            return _iceI_sendGroupMessageAsync(from, groupName, content, context, true).waitForResponseOrUserEx();
        }
        catch(UserException ex)
        {
            throw ex;
        }
        catch(com.zeroc.Ice.UserException ex)
        {
            throw new com.zeroc.Ice.UnknownUserException(ex.ice_id(), ex);
        }
    }

    default java.util.concurrent.CompletableFuture<java.lang.Boolean> sendGroupMessageAsync(String from, String groupName, String content)
    {
        return _iceI_sendGroupMessageAsync(from, groupName, content, com.zeroc.Ice.ObjectPrx.noExplicitContext, false);
    }

    default java.util.concurrent.CompletableFuture<java.lang.Boolean> sendGroupMessageAsync(String from, String groupName, String content, java.util.Map<String, String> context)
    {
        return _iceI_sendGroupMessageAsync(from, groupName, content, context, false);
    }

    /**
     * @hidden
     * @param iceP_from -
     * @param iceP_groupName -
     * @param iceP_content -
     * @param context -
     * @param sync -
     * @return -
     **/
    default com.zeroc.IceInternal.OutgoingAsync<java.lang.Boolean> _iceI_sendGroupMessageAsync(String iceP_from, String iceP_groupName, String iceP_content, java.util.Map<String, String> context, boolean sync)
    {
        com.zeroc.IceInternal.OutgoingAsync<java.lang.Boolean> f = new com.zeroc.IceInternal.OutgoingAsync<>(this, "sendGroupMessage", null, sync, _iceE_sendGroupMessage);
        f.invoke(true, context, null, ostr -> {
                     ostr.writeString(iceP_from);
                     ostr.writeString(iceP_groupName);
                     ostr.writeString(iceP_content);
                 }, istr -> {
                     boolean ret;
                     ret = istr.readBool();
                     return ret;
                 });
        return f;
    }

    /** @hidden */
    static final Class<?>[] _iceE_sendGroupMessage =
    {
        UserException.class
    };

    default MessageInfo[] getGroupHistory(String groupName)
        throws UserException
    {
        return getGroupHistory(groupName, com.zeroc.Ice.ObjectPrx.noExplicitContext);
    }

    default MessageInfo[] getGroupHistory(String groupName, java.util.Map<String, String> context)
        throws UserException
    {
        try
        {
            return _iceI_getGroupHistoryAsync(groupName, context, true).waitForResponseOrUserEx();
        }
        catch(UserException ex)
        {
            throw ex;
        }
        catch(com.zeroc.Ice.UserException ex)
        {
            throw new com.zeroc.Ice.UnknownUserException(ex.ice_id(), ex);
        }
    }

    default java.util.concurrent.CompletableFuture<MessageInfo[]> getGroupHistoryAsync(String groupName)
    {
        return _iceI_getGroupHistoryAsync(groupName, com.zeroc.Ice.ObjectPrx.noExplicitContext, false);
    }

    default java.util.concurrent.CompletableFuture<MessageInfo[]> getGroupHistoryAsync(String groupName, java.util.Map<String, String> context)
    {
        return _iceI_getGroupHistoryAsync(groupName, context, false);
    }

    /**
     * @hidden
     * @param iceP_groupName -
     * @param context -
     * @param sync -
     * @return -
     **/
    default com.zeroc.IceInternal.OutgoingAsync<MessageInfo[]> _iceI_getGroupHistoryAsync(String iceP_groupName, java.util.Map<String, String> context, boolean sync)
    {
        com.zeroc.IceInternal.OutgoingAsync<MessageInfo[]> f = new com.zeroc.IceInternal.OutgoingAsync<>(this, "getGroupHistory", null, sync, _iceE_getGroupHistory);
        f.invoke(true, context, null, ostr -> {
                     ostr.writeString(iceP_groupName);
                 }, istr -> {
                     MessageInfo[] ret;
                     ret = MessageSeqHelper.read(istr);
                     return ret;
                 });
        return f;
    }

    /** @hidden */
    static final Class<?>[] _iceE_getGroupHistory =
    {
        UserException.class
    };

    default boolean createGroup(String groupName, String creator, String[] members)
        throws UserException
    {
        return createGroup(groupName, creator, members, com.zeroc.Ice.ObjectPrx.noExplicitContext);
    }

    default boolean createGroup(String groupName, String creator, String[] members, java.util.Map<String, String> context)
        throws UserException
    {
        try
        {
            return _iceI_createGroupAsync(groupName, creator, members, context, true).waitForResponseOrUserEx();
        }
        catch(UserException ex)
        {
            throw ex;
        }
        catch(com.zeroc.Ice.UserException ex)
        {
            throw new com.zeroc.Ice.UnknownUserException(ex.ice_id(), ex);
        }
    }

    default java.util.concurrent.CompletableFuture<java.lang.Boolean> createGroupAsync(String groupName, String creator, String[] members)
    {
        return _iceI_createGroupAsync(groupName, creator, members, com.zeroc.Ice.ObjectPrx.noExplicitContext, false);
    }

    default java.util.concurrent.CompletableFuture<java.lang.Boolean> createGroupAsync(String groupName, String creator, String[] members, java.util.Map<String, String> context)
    {
        return _iceI_createGroupAsync(groupName, creator, members, context, false);
    }

    /**
     * @hidden
     * @param iceP_groupName -
     * @param iceP_creator -
     * @param iceP_members -
     * @param context -
     * @param sync -
     * @return -
     **/
    default com.zeroc.IceInternal.OutgoingAsync<java.lang.Boolean> _iceI_createGroupAsync(String iceP_groupName, String iceP_creator, String[] iceP_members, java.util.Map<String, String> context, boolean sync)
    {
        com.zeroc.IceInternal.OutgoingAsync<java.lang.Boolean> f = new com.zeroc.IceInternal.OutgoingAsync<>(this, "createGroup", null, sync, _iceE_createGroup);
        f.invoke(true, context, null, ostr -> {
                     ostr.writeString(iceP_groupName);
                     ostr.writeString(iceP_creator);
                     ostr.writeStringSeq(iceP_members);
                 }, istr -> {
                     boolean ret;
                     ret = istr.readBool();
                     return ret;
                 });
        return f;
    }

    /** @hidden */
    static final Class<?>[] _iceE_createGroup =
    {
        UserException.class
    };

    default boolean joinGroup(String username, String groupName)
        throws UserException
    {
        return joinGroup(username, groupName, com.zeroc.Ice.ObjectPrx.noExplicitContext);
    }

    default boolean joinGroup(String username, String groupName, java.util.Map<String, String> context)
        throws UserException
    {
        try
        {
            return _iceI_joinGroupAsync(username, groupName, context, true).waitForResponseOrUserEx();
        }
        catch(UserException ex)
        {
            throw ex;
        }
        catch(com.zeroc.Ice.UserException ex)
        {
            throw new com.zeroc.Ice.UnknownUserException(ex.ice_id(), ex);
        }
    }

    default java.util.concurrent.CompletableFuture<java.lang.Boolean> joinGroupAsync(String username, String groupName)
    {
        return _iceI_joinGroupAsync(username, groupName, com.zeroc.Ice.ObjectPrx.noExplicitContext, false);
    }

    default java.util.concurrent.CompletableFuture<java.lang.Boolean> joinGroupAsync(String username, String groupName, java.util.Map<String, String> context)
    {
        return _iceI_joinGroupAsync(username, groupName, context, false);
    }

    /**
     * @hidden
     * @param iceP_username -
     * @param iceP_groupName -
     * @param context -
     * @param sync -
     * @return -
     **/
    default com.zeroc.IceInternal.OutgoingAsync<java.lang.Boolean> _iceI_joinGroupAsync(String iceP_username, String iceP_groupName, java.util.Map<String, String> context, boolean sync)
    {
        com.zeroc.IceInternal.OutgoingAsync<java.lang.Boolean> f = new com.zeroc.IceInternal.OutgoingAsync<>(this, "joinGroup", null, sync, _iceE_joinGroup);
        f.invoke(true, context, null, ostr -> {
                     ostr.writeString(iceP_username);
                     ostr.writeString(iceP_groupName);
                 }, istr -> {
                     boolean ret;
                     ret = istr.readBool();
                     return ret;
                 });
        return f;
    }

    /** @hidden */
    static final Class<?>[] _iceE_joinGroup =
    {
        UserException.class
    };

    default boolean leaveGroup(String username, String groupName)
        throws UserException
    {
        return leaveGroup(username, groupName, com.zeroc.Ice.ObjectPrx.noExplicitContext);
    }

    default boolean leaveGroup(String username, String groupName, java.util.Map<String, String> context)
        throws UserException
    {
        try
        {
            return _iceI_leaveGroupAsync(username, groupName, context, true).waitForResponseOrUserEx();
        }
        catch(UserException ex)
        {
            throw ex;
        }
        catch(com.zeroc.Ice.UserException ex)
        {
            throw new com.zeroc.Ice.UnknownUserException(ex.ice_id(), ex);
        }
    }

    default java.util.concurrent.CompletableFuture<java.lang.Boolean> leaveGroupAsync(String username, String groupName)
    {
        return _iceI_leaveGroupAsync(username, groupName, com.zeroc.Ice.ObjectPrx.noExplicitContext, false);
    }

    default java.util.concurrent.CompletableFuture<java.lang.Boolean> leaveGroupAsync(String username, String groupName, java.util.Map<String, String> context)
    {
        return _iceI_leaveGroupAsync(username, groupName, context, false);
    }

    /**
     * @hidden
     * @param iceP_username -
     * @param iceP_groupName -
     * @param context -
     * @param sync -
     * @return -
     **/
    default com.zeroc.IceInternal.OutgoingAsync<java.lang.Boolean> _iceI_leaveGroupAsync(String iceP_username, String iceP_groupName, java.util.Map<String, String> context, boolean sync)
    {
        com.zeroc.IceInternal.OutgoingAsync<java.lang.Boolean> f = new com.zeroc.IceInternal.OutgoingAsync<>(this, "leaveGroup", null, sync, _iceE_leaveGroup);
        f.invoke(true, context, null, ostr -> {
                     ostr.writeString(iceP_username);
                     ostr.writeString(iceP_groupName);
                 }, istr -> {
                     boolean ret;
                     ret = istr.readBool();
                     return ret;
                 });
        return f;
    }

    /** @hidden */
    static final Class<?>[] _iceE_leaveGroup =
    {
        UserException.class
    };

    default GroupInfo[] getUserGroups(String username)
        throws UserException
    {
        return getUserGroups(username, com.zeroc.Ice.ObjectPrx.noExplicitContext);
    }

    default GroupInfo[] getUserGroups(String username, java.util.Map<String, String> context)
        throws UserException
    {
        try
        {
            return _iceI_getUserGroupsAsync(username, context, true).waitForResponseOrUserEx();
        }
        catch(UserException ex)
        {
            throw ex;
        }
        catch(com.zeroc.Ice.UserException ex)
        {
            throw new com.zeroc.Ice.UnknownUserException(ex.ice_id(), ex);
        }
    }

    default java.util.concurrent.CompletableFuture<GroupInfo[]> getUserGroupsAsync(String username)
    {
        return _iceI_getUserGroupsAsync(username, com.zeroc.Ice.ObjectPrx.noExplicitContext, false);
    }

    default java.util.concurrent.CompletableFuture<GroupInfo[]> getUserGroupsAsync(String username, java.util.Map<String, String> context)
    {
        return _iceI_getUserGroupsAsync(username, context, false);
    }

    /**
     * @hidden
     * @param iceP_username -
     * @param context -
     * @param sync -
     * @return -
     **/
    default com.zeroc.IceInternal.OutgoingAsync<GroupInfo[]> _iceI_getUserGroupsAsync(String iceP_username, java.util.Map<String, String> context, boolean sync)
    {
        com.zeroc.IceInternal.OutgoingAsync<GroupInfo[]> f = new com.zeroc.IceInternal.OutgoingAsync<>(this, "getUserGroups", null, sync, _iceE_getUserGroups);
        f.invoke(true, context, null, ostr -> {
                     ostr.writeString(iceP_username);
                 }, istr -> {
                     GroupInfo[] ret;
                     ret = GroupSeqHelper.read(istr);
                     return ret;
                 });
        return f;
    }

    /** @hidden */
    static final Class<?>[] _iceE_getUserGroups =
    {
        UserException.class
    };

    default String[] getGroupMembers(String groupName)
        throws UserException
    {
        return getGroupMembers(groupName, com.zeroc.Ice.ObjectPrx.noExplicitContext);
    }

    default String[] getGroupMembers(String groupName, java.util.Map<String, String> context)
        throws UserException
    {
        try
        {
            return _iceI_getGroupMembersAsync(groupName, context, true).waitForResponseOrUserEx();
        }
        catch(UserException ex)
        {
            throw ex;
        }
        catch(com.zeroc.Ice.UserException ex)
        {
            throw new com.zeroc.Ice.UnknownUserException(ex.ice_id(), ex);
        }
    }

    default java.util.concurrent.CompletableFuture<String[]> getGroupMembersAsync(String groupName)
    {
        return _iceI_getGroupMembersAsync(groupName, com.zeroc.Ice.ObjectPrx.noExplicitContext, false);
    }

    default java.util.concurrent.CompletableFuture<String[]> getGroupMembersAsync(String groupName, java.util.Map<String, String> context)
    {
        return _iceI_getGroupMembersAsync(groupName, context, false);
    }

    /**
     * @hidden
     * @param iceP_groupName -
     * @param context -
     * @param sync -
     * @return -
     **/
    default com.zeroc.IceInternal.OutgoingAsync<String[]> _iceI_getGroupMembersAsync(String iceP_groupName, java.util.Map<String, String> context, boolean sync)
    {
        com.zeroc.IceInternal.OutgoingAsync<String[]> f = new com.zeroc.IceInternal.OutgoingAsync<>(this, "getGroupMembers", null, sync, _iceE_getGroupMembers);
        f.invoke(true, context, null, ostr -> {
                     ostr.writeString(iceP_groupName);
                 }, istr -> {
                     String[] ret;
                     ret = istr.readStringSeq();
                     return ret;
                 });
        return f;
    }

    /** @hidden */
    static final Class<?>[] _iceE_getGroupMembers =
    {
        UserException.class
    };

    default boolean sendAudio(String from, String to, String audioId, int size, int duration)
        throws UserException
    {
        return sendAudio(from, to, audioId, size, duration, com.zeroc.Ice.ObjectPrx.noExplicitContext);
    }

    default boolean sendAudio(String from, String to, String audioId, int size, int duration, java.util.Map<String, String> context)
        throws UserException
    {
        try
        {
            return _iceI_sendAudioAsync(from, to, audioId, size, duration, context, true).waitForResponseOrUserEx();
        }
        catch(UserException ex)
        {
            throw ex;
        }
        catch(com.zeroc.Ice.UserException ex)
        {
            throw new com.zeroc.Ice.UnknownUserException(ex.ice_id(), ex);
        }
    }

    default java.util.concurrent.CompletableFuture<java.lang.Boolean> sendAudioAsync(String from, String to, String audioId, int size, int duration)
    {
        return _iceI_sendAudioAsync(from, to, audioId, size, duration, com.zeroc.Ice.ObjectPrx.noExplicitContext, false);
    }

    default java.util.concurrent.CompletableFuture<java.lang.Boolean> sendAudioAsync(String from, String to, String audioId, int size, int duration, java.util.Map<String, String> context)
    {
        return _iceI_sendAudioAsync(from, to, audioId, size, duration, context, false);
    }

    /**
     * @hidden
     * @param iceP_from -
     * @param iceP_to -
     * @param iceP_audioId -
     * @param iceP_size -
     * @param iceP_duration -
     * @param context -
     * @param sync -
     * @return -
     **/
    default com.zeroc.IceInternal.OutgoingAsync<java.lang.Boolean> _iceI_sendAudioAsync(String iceP_from, String iceP_to, String iceP_audioId, int iceP_size, int iceP_duration, java.util.Map<String, String> context, boolean sync)
    {
        com.zeroc.IceInternal.OutgoingAsync<java.lang.Boolean> f = new com.zeroc.IceInternal.OutgoingAsync<>(this, "sendAudio", null, sync, _iceE_sendAudio);
        f.invoke(true, context, null, ostr -> {
                     ostr.writeString(iceP_from);
                     ostr.writeString(iceP_to);
                     ostr.writeString(iceP_audioId);
                     ostr.writeInt(iceP_size);
                     ostr.writeInt(iceP_duration);
                 }, istr -> {
                     boolean ret;
                     ret = istr.readBool();
                     return ret;
                 });
        return f;
    }

    /** @hidden */
    static final Class<?>[] _iceE_sendAudio =
    {
        UserException.class
    };

    default boolean sendGroupAudio(String from, String groupName, String audioId, int size, int duration)
        throws UserException
    {
        return sendGroupAudio(from, groupName, audioId, size, duration, com.zeroc.Ice.ObjectPrx.noExplicitContext);
    }

    default boolean sendGroupAudio(String from, String groupName, String audioId, int size, int duration, java.util.Map<String, String> context)
        throws UserException
    {
        try
        {
            return _iceI_sendGroupAudioAsync(from, groupName, audioId, size, duration, context, true).waitForResponseOrUserEx();
        }
        catch(UserException ex)
        {
            throw ex;
        }
        catch(com.zeroc.Ice.UserException ex)
        {
            throw new com.zeroc.Ice.UnknownUserException(ex.ice_id(), ex);
        }
    }

    default java.util.concurrent.CompletableFuture<java.lang.Boolean> sendGroupAudioAsync(String from, String groupName, String audioId, int size, int duration)
    {
        return _iceI_sendGroupAudioAsync(from, groupName, audioId, size, duration, com.zeroc.Ice.ObjectPrx.noExplicitContext, false);
    }

    default java.util.concurrent.CompletableFuture<java.lang.Boolean> sendGroupAudioAsync(String from, String groupName, String audioId, int size, int duration, java.util.Map<String, String> context)
    {
        return _iceI_sendGroupAudioAsync(from, groupName, audioId, size, duration, context, false);
    }

    /**
     * @hidden
     * @param iceP_from -
     * @param iceP_groupName -
     * @param iceP_audioId -
     * @param iceP_size -
     * @param iceP_duration -
     * @param context -
     * @param sync -
     * @return -
     **/
    default com.zeroc.IceInternal.OutgoingAsync<java.lang.Boolean> _iceI_sendGroupAudioAsync(String iceP_from, String iceP_groupName, String iceP_audioId, int iceP_size, int iceP_duration, java.util.Map<String, String> context, boolean sync)
    {
        com.zeroc.IceInternal.OutgoingAsync<java.lang.Boolean> f = new com.zeroc.IceInternal.OutgoingAsync<>(this, "sendGroupAudio", null, sync, _iceE_sendGroupAudio);
        f.invoke(true, context, null, ostr -> {
                     ostr.writeString(iceP_from);
                     ostr.writeString(iceP_groupName);
                     ostr.writeString(iceP_audioId);
                     ostr.writeInt(iceP_size);
                     ostr.writeInt(iceP_duration);
                 }, istr -> {
                     boolean ret;
                     ret = istr.readBool();
                     return ret;
                 });
        return f;
    }

    /** @hidden */
    static final Class<?>[] _iceE_sendGroupAudio =
    {
        UserException.class
    };

    default AudioInfo[] getPrivateAudioHistory(String username, String target)
        throws UserException
    {
        return getPrivateAudioHistory(username, target, com.zeroc.Ice.ObjectPrx.noExplicitContext);
    }

    default AudioInfo[] getPrivateAudioHistory(String username, String target, java.util.Map<String, String> context)
        throws UserException
    {
        try
        {
            return _iceI_getPrivateAudioHistoryAsync(username, target, context, true).waitForResponseOrUserEx();
        }
        catch(UserException ex)
        {
            throw ex;
        }
        catch(com.zeroc.Ice.UserException ex)
        {
            throw new com.zeroc.Ice.UnknownUserException(ex.ice_id(), ex);
        }
    }

    default java.util.concurrent.CompletableFuture<AudioInfo[]> getPrivateAudioHistoryAsync(String username, String target)
    {
        return _iceI_getPrivateAudioHistoryAsync(username, target, com.zeroc.Ice.ObjectPrx.noExplicitContext, false);
    }

    default java.util.concurrent.CompletableFuture<AudioInfo[]> getPrivateAudioHistoryAsync(String username, String target, java.util.Map<String, String> context)
    {
        return _iceI_getPrivateAudioHistoryAsync(username, target, context, false);
    }

    /**
     * @hidden
     * @param iceP_username -
     * @param iceP_target -
     * @param context -
     * @param sync -
     * @return -
     **/
    default com.zeroc.IceInternal.OutgoingAsync<AudioInfo[]> _iceI_getPrivateAudioHistoryAsync(String iceP_username, String iceP_target, java.util.Map<String, String> context, boolean sync)
    {
        com.zeroc.IceInternal.OutgoingAsync<AudioInfo[]> f = new com.zeroc.IceInternal.OutgoingAsync<>(this, "getPrivateAudioHistory", null, sync, _iceE_getPrivateAudioHistory);
        f.invoke(true, context, null, ostr -> {
                     ostr.writeString(iceP_username);
                     ostr.writeString(iceP_target);
                 }, istr -> {
                     AudioInfo[] ret;
                     ret = AudioSeqHelper.read(istr);
                     return ret;
                 });
        return f;
    }

    /** @hidden */
    static final Class<?>[] _iceE_getPrivateAudioHistory =
    {
        UserException.class
    };

    default AudioInfo[] getGroupAudioHistory(String groupName)
        throws UserException
    {
        return getGroupAudioHistory(groupName, com.zeroc.Ice.ObjectPrx.noExplicitContext);
    }

    default AudioInfo[] getGroupAudioHistory(String groupName, java.util.Map<String, String> context)
        throws UserException
    {
        try
        {
            return _iceI_getGroupAudioHistoryAsync(groupName, context, true).waitForResponseOrUserEx();
        }
        catch(UserException ex)
        {
            throw ex;
        }
        catch(com.zeroc.Ice.UserException ex)
        {
            throw new com.zeroc.Ice.UnknownUserException(ex.ice_id(), ex);
        }
    }

    default java.util.concurrent.CompletableFuture<AudioInfo[]> getGroupAudioHistoryAsync(String groupName)
    {
        return _iceI_getGroupAudioHistoryAsync(groupName, com.zeroc.Ice.ObjectPrx.noExplicitContext, false);
    }

    default java.util.concurrent.CompletableFuture<AudioInfo[]> getGroupAudioHistoryAsync(String groupName, java.util.Map<String, String> context)
    {
        return _iceI_getGroupAudioHistoryAsync(groupName, context, false);
    }

    /**
     * @hidden
     * @param iceP_groupName -
     * @param context -
     * @param sync -
     * @return -
     **/
    default com.zeroc.IceInternal.OutgoingAsync<AudioInfo[]> _iceI_getGroupAudioHistoryAsync(String iceP_groupName, java.util.Map<String, String> context, boolean sync)
    {
        com.zeroc.IceInternal.OutgoingAsync<AudioInfo[]> f = new com.zeroc.IceInternal.OutgoingAsync<>(this, "getGroupAudioHistory", null, sync, _iceE_getGroupAudioHistory);
        f.invoke(true, context, null, ostr -> {
                     ostr.writeString(iceP_groupName);
                 }, istr -> {
                     AudioInfo[] ret;
                     ret = AudioSeqHelper.read(istr);
                     return ret;
                 });
        return f;
    }

    /** @hidden */
    static final Class<?>[] _iceE_getGroupAudioHistory =
    {
        UserException.class
    };

    default String[] getOnlineUsers()
        throws UserException
    {
        return getOnlineUsers(com.zeroc.Ice.ObjectPrx.noExplicitContext);
    }

    default String[] getOnlineUsers(java.util.Map<String, String> context)
        throws UserException
    {
        try
        {
            return _iceI_getOnlineUsersAsync(context, true).waitForResponseOrUserEx();
        }
        catch(UserException ex)
        {
            throw ex;
        }
        catch(com.zeroc.Ice.UserException ex)
        {
            throw new com.zeroc.Ice.UnknownUserException(ex.ice_id(), ex);
        }
    }

    default java.util.concurrent.CompletableFuture<String[]> getOnlineUsersAsync()
    {
        return _iceI_getOnlineUsersAsync(com.zeroc.Ice.ObjectPrx.noExplicitContext, false);
    }

    default java.util.concurrent.CompletableFuture<String[]> getOnlineUsersAsync(java.util.Map<String, String> context)
    {
        return _iceI_getOnlineUsersAsync(context, false);
    }

    /**
     * @hidden
     * @param context -
     * @param sync -
     * @return -
     **/
    default com.zeroc.IceInternal.OutgoingAsync<String[]> _iceI_getOnlineUsersAsync(java.util.Map<String, String> context, boolean sync)
    {
        com.zeroc.IceInternal.OutgoingAsync<String[]> f = new com.zeroc.IceInternal.OutgoingAsync<>(this, "getOnlineUsers", null, sync, _iceE_getOnlineUsers);
        f.invoke(true, context, null, null, istr -> {
                     String[] ret;
                     ret = istr.readStringSeq();
                     return ret;
                 });
        return f;
    }

    /** @hidden */
    static final Class<?>[] _iceE_getOnlineUsers =
    {
        UserException.class
    };

    default UserInfo[] getAllUsers()
        throws UserException
    {
        return getAllUsers(com.zeroc.Ice.ObjectPrx.noExplicitContext);
    }

    default UserInfo[] getAllUsers(java.util.Map<String, String> context)
        throws UserException
    {
        try
        {
            return _iceI_getAllUsersAsync(context, true).waitForResponseOrUserEx();
        }
        catch(UserException ex)
        {
            throw ex;
        }
        catch(com.zeroc.Ice.UserException ex)
        {
            throw new com.zeroc.Ice.UnknownUserException(ex.ice_id(), ex);
        }
    }

    default java.util.concurrent.CompletableFuture<UserInfo[]> getAllUsersAsync()
    {
        return _iceI_getAllUsersAsync(com.zeroc.Ice.ObjectPrx.noExplicitContext, false);
    }

    default java.util.concurrent.CompletableFuture<UserInfo[]> getAllUsersAsync(java.util.Map<String, String> context)
    {
        return _iceI_getAllUsersAsync(context, false);
    }

    /**
     * @hidden
     * @param context -
     * @param sync -
     * @return -
     **/
    default com.zeroc.IceInternal.OutgoingAsync<UserInfo[]> _iceI_getAllUsersAsync(java.util.Map<String, String> context, boolean sync)
    {
        com.zeroc.IceInternal.OutgoingAsync<UserInfo[]> f = new com.zeroc.IceInternal.OutgoingAsync<>(this, "getAllUsers", null, sync, _iceE_getAllUsers);
        f.invoke(true, context, null, null, istr -> {
                     UserInfo[] ret;
                     ret = UserSeqHelper.read(istr);
                     return ret;
                 });
        return f;
    }

    /** @hidden */
    static final Class<?>[] _iceE_getAllUsers =
    {
        UserException.class
    };

    default boolean isUserOnline(String username)
        throws UserException
    {
        return isUserOnline(username, com.zeroc.Ice.ObjectPrx.noExplicitContext);
    }

    default boolean isUserOnline(String username, java.util.Map<String, String> context)
        throws UserException
    {
        try
        {
            return _iceI_isUserOnlineAsync(username, context, true).waitForResponseOrUserEx();
        }
        catch(UserException ex)
        {
            throw ex;
        }
        catch(com.zeroc.Ice.UserException ex)
        {
            throw new com.zeroc.Ice.UnknownUserException(ex.ice_id(), ex);
        }
    }

    default java.util.concurrent.CompletableFuture<java.lang.Boolean> isUserOnlineAsync(String username)
    {
        return _iceI_isUserOnlineAsync(username, com.zeroc.Ice.ObjectPrx.noExplicitContext, false);
    }

    default java.util.concurrent.CompletableFuture<java.lang.Boolean> isUserOnlineAsync(String username, java.util.Map<String, String> context)
    {
        return _iceI_isUserOnlineAsync(username, context, false);
    }

    /**
     * @hidden
     * @param iceP_username -
     * @param context -
     * @param sync -
     * @return -
     **/
    default com.zeroc.IceInternal.OutgoingAsync<java.lang.Boolean> _iceI_isUserOnlineAsync(String iceP_username, java.util.Map<String, String> context, boolean sync)
    {
        com.zeroc.IceInternal.OutgoingAsync<java.lang.Boolean> f = new com.zeroc.IceInternal.OutgoingAsync<>(this, "isUserOnline", null, sync, _iceE_isUserOnline);
        f.invoke(true, context, null, ostr -> {
                     ostr.writeString(iceP_username);
                 }, istr -> {
                     boolean ret;
                     ret = istr.readBool();
                     return ret;
                 });
        return f;
    }

    /** @hidden */
    static final Class<?>[] _iceE_isUserOnline =
    {
        UserException.class
    };

    default String getServerStatus()
        throws UserException
    {
        return getServerStatus(com.zeroc.Ice.ObjectPrx.noExplicitContext);
    }

    default String getServerStatus(java.util.Map<String, String> context)
        throws UserException
    {
        try
        {
            return _iceI_getServerStatusAsync(context, true).waitForResponseOrUserEx();
        }
        catch(UserException ex)
        {
            throw ex;
        }
        catch(com.zeroc.Ice.UserException ex)
        {
            throw new com.zeroc.Ice.UnknownUserException(ex.ice_id(), ex);
        }
    }

    default java.util.concurrent.CompletableFuture<java.lang.String> getServerStatusAsync()
    {
        return _iceI_getServerStatusAsync(com.zeroc.Ice.ObjectPrx.noExplicitContext, false);
    }

    default java.util.concurrent.CompletableFuture<java.lang.String> getServerStatusAsync(java.util.Map<String, String> context)
    {
        return _iceI_getServerStatusAsync(context, false);
    }

    /**
     * @hidden
     * @param context -
     * @param sync -
     * @return -
     **/
    default com.zeroc.IceInternal.OutgoingAsync<java.lang.String> _iceI_getServerStatusAsync(java.util.Map<String, String> context, boolean sync)
    {
        com.zeroc.IceInternal.OutgoingAsync<java.lang.String> f = new com.zeroc.IceInternal.OutgoingAsync<>(this, "getServerStatus", com.zeroc.Ice.OperationMode.Idempotent, sync, _iceE_getServerStatus);
        f.invoke(true, context, null, null, istr -> {
                     String ret;
                     ret = istr.readString();
                     return ret;
                 });
        return f;
    }

    /** @hidden */
    static final Class<?>[] _iceE_getServerStatus =
    {
        UserException.class
    };

    /**
     * Contacts the remote server to verify that the object implements this type.
     * Raises a local exception if a communication error occurs.
     * @param obj The untyped proxy.
     * @return A proxy for this type, or null if the object does not support this type.
     **/
    static ChatServicePrx checkedCast(com.zeroc.Ice.ObjectPrx obj)
    {
        return com.zeroc.Ice.ObjectPrx._checkedCast(obj, ice_staticId(), ChatServicePrx.class, _ChatServicePrxI.class);
    }

    /**
     * Contacts the remote server to verify that the object implements this type.
     * Raises a local exception if a communication error occurs.
     * @param obj The untyped proxy.
     * @param context The Context map to send with the invocation.
     * @return A proxy for this type, or null if the object does not support this type.
     **/
    static ChatServicePrx checkedCast(com.zeroc.Ice.ObjectPrx obj, java.util.Map<String, String> context)
    {
        return com.zeroc.Ice.ObjectPrx._checkedCast(obj, context, ice_staticId(), ChatServicePrx.class, _ChatServicePrxI.class);
    }

    /**
     * Contacts the remote server to verify that a facet of the object implements this type.
     * Raises a local exception if a communication error occurs.
     * @param obj The untyped proxy.
     * @param facet The name of the desired facet.
     * @return A proxy for this type, or null if the object does not support this type.
     **/
    static ChatServicePrx checkedCast(com.zeroc.Ice.ObjectPrx obj, String facet)
    {
        return com.zeroc.Ice.ObjectPrx._checkedCast(obj, facet, ice_staticId(), ChatServicePrx.class, _ChatServicePrxI.class);
    }

    /**
     * Contacts the remote server to verify that a facet of the object implements this type.
     * Raises a local exception if a communication error occurs.
     * @param obj The untyped proxy.
     * @param facet The name of the desired facet.
     * @param context The Context map to send with the invocation.
     * @return A proxy for this type, or null if the object does not support this type.
     **/
    static ChatServicePrx checkedCast(com.zeroc.Ice.ObjectPrx obj, String facet, java.util.Map<String, String> context)
    {
        return com.zeroc.Ice.ObjectPrx._checkedCast(obj, facet, context, ice_staticId(), ChatServicePrx.class, _ChatServicePrxI.class);
    }

    /**
     * Downcasts the given proxy to this type without contacting the remote server.
     * @param obj The untyped proxy.
     * @return A proxy for this type.
     **/
    static ChatServicePrx uncheckedCast(com.zeroc.Ice.ObjectPrx obj)
    {
        return com.zeroc.Ice.ObjectPrx._uncheckedCast(obj, ChatServicePrx.class, _ChatServicePrxI.class);
    }

    /**
     * Downcasts the given proxy to this type without contacting the remote server.
     * @param obj The untyped proxy.
     * @param facet The name of the desired facet.
     * @return A proxy for this type.
     **/
    static ChatServicePrx uncheckedCast(com.zeroc.Ice.ObjectPrx obj, String facet)
    {
        return com.zeroc.Ice.ObjectPrx._uncheckedCast(obj, facet, ChatServicePrx.class, _ChatServicePrxI.class);
    }

    /**
     * Returns a proxy that is identical to this proxy, except for the per-proxy context.
     * @param newContext The context for the new proxy.
     * @return A proxy with the specified per-proxy context.
     **/
    @Override
    default ChatServicePrx ice_context(java.util.Map<String, String> newContext)
    {
        return (ChatServicePrx)_ice_context(newContext);
    }

    /**
     * Returns a proxy that is identical to this proxy, except for the adapter ID.
     * @param newAdapterId The adapter ID for the new proxy.
     * @return A proxy with the specified adapter ID.
     **/
    @Override
    default ChatServicePrx ice_adapterId(String newAdapterId)
    {
        return (ChatServicePrx)_ice_adapterId(newAdapterId);
    }

    /**
     * Returns a proxy that is identical to this proxy, except for the endpoints.
     * @param newEndpoints The endpoints for the new proxy.
     * @return A proxy with the specified endpoints.
     **/
    @Override
    default ChatServicePrx ice_endpoints(com.zeroc.Ice.Endpoint[] newEndpoints)
    {
        return (ChatServicePrx)_ice_endpoints(newEndpoints);
    }

    /**
     * Returns a proxy that is identical to this proxy, except for the locator cache timeout.
     * @param newTimeout The new locator cache timeout (in seconds).
     * @return A proxy with the specified locator cache timeout.
     **/
    @Override
    default ChatServicePrx ice_locatorCacheTimeout(int newTimeout)
    {
        return (ChatServicePrx)_ice_locatorCacheTimeout(newTimeout);
    }

    /**
     * Returns a proxy that is identical to this proxy, except for the invocation timeout.
     * @param newTimeout The new invocation timeout (in seconds).
     * @return A proxy with the specified invocation timeout.
     **/
    @Override
    default ChatServicePrx ice_invocationTimeout(int newTimeout)
    {
        return (ChatServicePrx)_ice_invocationTimeout(newTimeout);
    }

    /**
     * Returns a proxy that is identical to this proxy, except for connection caching.
     * @param newCache <code>true</code> if the new proxy should cache connections; <code>false</code> otherwise.
     * @return A proxy with the specified caching policy.
     **/
    @Override
    default ChatServicePrx ice_connectionCached(boolean newCache)
    {
        return (ChatServicePrx)_ice_connectionCached(newCache);
    }

    /**
     * Returns a proxy that is identical to this proxy, except for the endpoint selection policy.
     * @param newType The new endpoint selection policy.
     * @return A proxy with the specified endpoint selection policy.
     **/
    @Override
    default ChatServicePrx ice_endpointSelection(com.zeroc.Ice.EndpointSelectionType newType)
    {
        return (ChatServicePrx)_ice_endpointSelection(newType);
    }

    /**
     * Returns a proxy that is identical to this proxy, except for how it selects endpoints.
     * @param b If <code>b</code> is <code>true</code>, only endpoints that use a secure transport are
     * used by the new proxy. If <code>b</code> is false, the returned proxy uses both secure and
     * insecure endpoints.
     * @return A proxy with the specified selection policy.
     **/
    @Override
    default ChatServicePrx ice_secure(boolean b)
    {
        return (ChatServicePrx)_ice_secure(b);
    }

    /**
     * Returns a proxy that is identical to this proxy, except for the encoding used to marshal parameters.
     * @param e The encoding version to use to marshal request parameters.
     * @return A proxy with the specified encoding version.
     **/
    @Override
    default ChatServicePrx ice_encodingVersion(com.zeroc.Ice.EncodingVersion e)
    {
        return (ChatServicePrx)_ice_encodingVersion(e);
    }

    /**
     * Returns a proxy that is identical to this proxy, except for its endpoint selection policy.
     * @param b If <code>b</code> is <code>true</code>, the new proxy will use secure endpoints for invocations
     * and only use insecure endpoints if an invocation cannot be made via secure endpoints. If <code>b</code> is
     * <code>false</code>, the proxy prefers insecure endpoints to secure ones.
     * @return A proxy with the specified selection policy.
     **/
    @Override
    default ChatServicePrx ice_preferSecure(boolean b)
    {
        return (ChatServicePrx)_ice_preferSecure(b);
    }

    /**
     * Returns a proxy that is identical to this proxy, except for the router.
     * @param router The router for the new proxy.
     * @return A proxy with the specified router.
     **/
    @Override
    default ChatServicePrx ice_router(com.zeroc.Ice.RouterPrx router)
    {
        return (ChatServicePrx)_ice_router(router);
    }

    /**
     * Returns a proxy that is identical to this proxy, except for the locator.
     * @param locator The locator for the new proxy.
     * @return A proxy with the specified locator.
     **/
    @Override
    default ChatServicePrx ice_locator(com.zeroc.Ice.LocatorPrx locator)
    {
        return (ChatServicePrx)_ice_locator(locator);
    }

    /**
     * Returns a proxy that is identical to this proxy, except for collocation optimization.
     * @param b <code>true</code> if the new proxy enables collocation optimization; <code>false</code> otherwise.
     * @return A proxy with the specified collocation optimization.
     **/
    @Override
    default ChatServicePrx ice_collocationOptimized(boolean b)
    {
        return (ChatServicePrx)_ice_collocationOptimized(b);
    }

    /**
     * Returns a proxy that is identical to this proxy, but uses twoway invocations.
     * @return A proxy that uses twoway invocations.
     **/
    @Override
    default ChatServicePrx ice_twoway()
    {
        return (ChatServicePrx)_ice_twoway();
    }

    /**
     * Returns a proxy that is identical to this proxy, but uses oneway invocations.
     * @return A proxy that uses oneway invocations.
     **/
    @Override
    default ChatServicePrx ice_oneway()
    {
        return (ChatServicePrx)_ice_oneway();
    }

    /**
     * Returns a proxy that is identical to this proxy, but uses batch oneway invocations.
     * @return A proxy that uses batch oneway invocations.
     **/
    @Override
    default ChatServicePrx ice_batchOneway()
    {
        return (ChatServicePrx)_ice_batchOneway();
    }

    /**
     * Returns a proxy that is identical to this proxy, but uses datagram invocations.
     * @return A proxy that uses datagram invocations.
     **/
    @Override
    default ChatServicePrx ice_datagram()
    {
        return (ChatServicePrx)_ice_datagram();
    }

    /**
     * Returns a proxy that is identical to this proxy, but uses batch datagram invocations.
     * @return A proxy that uses batch datagram invocations.
     **/
    @Override
    default ChatServicePrx ice_batchDatagram()
    {
        return (ChatServicePrx)_ice_batchDatagram();
    }

    /**
     * Returns a proxy that is identical to this proxy, except for compression.
     * @param co <code>true</code> enables compression for the new proxy; <code>false</code> disables compression.
     * @return A proxy with the specified compression setting.
     **/
    @Override
    default ChatServicePrx ice_compress(boolean co)
    {
        return (ChatServicePrx)_ice_compress(co);
    }

    /**
     * Returns a proxy that is identical to this proxy, except for its connection timeout setting.
     * @param t The connection timeout for the proxy in milliseconds.
     * @return A proxy with the specified timeout.
     **/
    @Override
    default ChatServicePrx ice_timeout(int t)
    {
        return (ChatServicePrx)_ice_timeout(t);
    }

    /**
     * Returns a proxy that is identical to this proxy, except for its connection ID.
     * @param connectionId The connection ID for the new proxy. An empty string removes the connection ID.
     * @return A proxy with the specified connection ID.
     **/
    @Override
    default ChatServicePrx ice_connectionId(String connectionId)
    {
        return (ChatServicePrx)_ice_connectionId(connectionId);
    }

    /**
     * Returns a proxy that is identical to this proxy, except it's a fixed proxy bound
     * the given connection.@param connection The fixed proxy connection.
     * @return A fixed proxy bound to the given connection.
     **/
    @Override
    default ChatServicePrx ice_fixed(com.zeroc.Ice.Connection connection)
    {
        return (ChatServicePrx)_ice_fixed(connection);
    }

    static String ice_staticId()
    {
        return "::chat::ChatService";
    }
}
