//
// Copyright (c) ZeroC, Inc. All rights reserved.
//
//
// Ice version 3.7.10
//
// <auto-generated>
//
// Generated from file `chat.ice'
//
// Warning: do not edit this file.
//
// </auto-generated>
//

package chat;

public interface ChatService extends com.zeroc.Ice.Object
{
    boolean login(String username, com.zeroc.Ice.Current current)
        throws UserException;

    boolean logout(String username, com.zeroc.Ice.Current current)
        throws UserException;

    boolean sendMessage(String from, String to, String content, com.zeroc.Ice.Current current)
        throws UserException;

    MessageInfo[] getPrivateHistory(String username, String target, com.zeroc.Ice.Current current)
        throws UserException;

    boolean sendGroupMessage(String from, String groupName, String content, com.zeroc.Ice.Current current)
        throws UserException;

    MessageInfo[] getGroupHistory(String groupName, com.zeroc.Ice.Current current)
        throws UserException;

    boolean createGroup(String groupName, String creator, String[] members, com.zeroc.Ice.Current current)
        throws UserException;

    boolean joinGroup(String username, String groupName, com.zeroc.Ice.Current current)
        throws UserException;

    boolean leaveGroup(String username, String groupName, com.zeroc.Ice.Current current)
        throws UserException;

    GroupInfo[] getUserGroups(String username, com.zeroc.Ice.Current current)
        throws UserException;

    String[] getGroupMembers(String groupName, com.zeroc.Ice.Current current)
        throws UserException;

    boolean sendAudio(String from, String to, String audioId, int size, int duration, com.zeroc.Ice.Current current)
        throws UserException;

    boolean sendGroupAudio(String from, String groupName, String audioId, int size, int duration, com.zeroc.Ice.Current current)
        throws UserException;

    AudioInfo[] getPrivateAudioHistory(String username, String target, com.zeroc.Ice.Current current)
        throws UserException;

    AudioInfo[] getGroupAudioHistory(String groupName, com.zeroc.Ice.Current current)
        throws UserException;

    String[] getOnlineUsers(com.zeroc.Ice.Current current)
        throws UserException;

    UserInfo[] getAllUsers(com.zeroc.Ice.Current current)
        throws UserException;

    boolean isUserOnline(String username, com.zeroc.Ice.Current current)
        throws UserException;

    String getServerStatus(com.zeroc.Ice.Current current)
        throws UserException;

    /** @hidden */
    static final String[] _iceIds =
    {
        "::Ice::Object",
        "::chat::ChatService"
    };

    @Override
    default String[] ice_ids(com.zeroc.Ice.Current current)
    {
        return _iceIds;
    }

    @Override
    default String ice_id(com.zeroc.Ice.Current current)
    {
        return ice_staticId();
    }

    static String ice_staticId()
    {
        return "::chat::ChatService";
    }

    /**
     * @hidden
     * @param obj -
     * @param inS -
     * @param current -
     * @return -
     * @throws com.zeroc.Ice.UserException -
    **/
    static java.util.concurrent.CompletionStage<com.zeroc.Ice.OutputStream> _iceD_login(ChatService obj, final com.zeroc.IceInternal.Incoming inS, com.zeroc.Ice.Current current)
        throws com.zeroc.Ice.UserException
    {
        com.zeroc.Ice.Object._iceCheckMode(null, current.mode);
        com.zeroc.Ice.InputStream istr = inS.startReadParams();
        String iceP_username;
        iceP_username = istr.readString();
        inS.endReadParams();
        boolean ret = obj.login(iceP_username, current);
        com.zeroc.Ice.OutputStream ostr = inS.startWriteParams();
        ostr.writeBool(ret);
        inS.endWriteParams(ostr);
        return inS.setResult(ostr);
    }

    /**
     * @hidden
     * @param obj -
     * @param inS -
     * @param current -
     * @return -
     * @throws com.zeroc.Ice.UserException -
    **/
    static java.util.concurrent.CompletionStage<com.zeroc.Ice.OutputStream> _iceD_logout(ChatService obj, final com.zeroc.IceInternal.Incoming inS, com.zeroc.Ice.Current current)
        throws com.zeroc.Ice.UserException
    {
        com.zeroc.Ice.Object._iceCheckMode(null, current.mode);
        com.zeroc.Ice.InputStream istr = inS.startReadParams();
        String iceP_username;
        iceP_username = istr.readString();
        inS.endReadParams();
        boolean ret = obj.logout(iceP_username, current);
        com.zeroc.Ice.OutputStream ostr = inS.startWriteParams();
        ostr.writeBool(ret);
        inS.endWriteParams(ostr);
        return inS.setResult(ostr);
    }

    /**
     * @hidden
     * @param obj -
     * @param inS -
     * @param current -
     * @return -
     * @throws com.zeroc.Ice.UserException -
    **/
    static java.util.concurrent.CompletionStage<com.zeroc.Ice.OutputStream> _iceD_sendMessage(ChatService obj, final com.zeroc.IceInternal.Incoming inS, com.zeroc.Ice.Current current)
        throws com.zeroc.Ice.UserException
    {
        com.zeroc.Ice.Object._iceCheckMode(null, current.mode);
        com.zeroc.Ice.InputStream istr = inS.startReadParams();
        String iceP_from;
        String iceP_to;
        String iceP_content;
        iceP_from = istr.readString();
        iceP_to = istr.readString();
        iceP_content = istr.readString();
        inS.endReadParams();
        boolean ret = obj.sendMessage(iceP_from, iceP_to, iceP_content, current);
        com.zeroc.Ice.OutputStream ostr = inS.startWriteParams();
        ostr.writeBool(ret);
        inS.endWriteParams(ostr);
        return inS.setResult(ostr);
    }

    /**
     * @hidden
     * @param obj -
     * @param inS -
     * @param current -
     * @return -
     * @throws com.zeroc.Ice.UserException -
    **/
    static java.util.concurrent.CompletionStage<com.zeroc.Ice.OutputStream> _iceD_getPrivateHistory(ChatService obj, final com.zeroc.IceInternal.Incoming inS, com.zeroc.Ice.Current current)
        throws com.zeroc.Ice.UserException
    {
        com.zeroc.Ice.Object._iceCheckMode(null, current.mode);
        com.zeroc.Ice.InputStream istr = inS.startReadParams();
        String iceP_username;
        String iceP_target;
        iceP_username = istr.readString();
        iceP_target = istr.readString();
        inS.endReadParams();
        MessageInfo[] ret = obj.getPrivateHistory(iceP_username, iceP_target, current);
        com.zeroc.Ice.OutputStream ostr = inS.startWriteParams();
        MessageSeqHelper.write(ostr, ret);
        inS.endWriteParams(ostr);
        return inS.setResult(ostr);
    }

    /**
     * @hidden
     * @param obj -
     * @param inS -
     * @param current -
     * @return -
     * @throws com.zeroc.Ice.UserException -
    **/
    static java.util.concurrent.CompletionStage<com.zeroc.Ice.OutputStream> _iceD_sendGroupMessage(ChatService obj, final com.zeroc.IceInternal.Incoming inS, com.zeroc.Ice.Current current)
        throws com.zeroc.Ice.UserException
    {
        com.zeroc.Ice.Object._iceCheckMode(null, current.mode);
        com.zeroc.Ice.InputStream istr = inS.startReadParams();
        String iceP_from;
        String iceP_groupName;
        String iceP_content;
        iceP_from = istr.readString();
        iceP_groupName = istr.readString();
        iceP_content = istr.readString();
        inS.endReadParams();
        boolean ret = obj.sendGroupMessage(iceP_from, iceP_groupName, iceP_content, current);
        com.zeroc.Ice.OutputStream ostr = inS.startWriteParams();
        ostr.writeBool(ret);
        inS.endWriteParams(ostr);
        return inS.setResult(ostr);
    }

    /**
     * @hidden
     * @param obj -
     * @param inS -
     * @param current -
     * @return -
     * @throws com.zeroc.Ice.UserException -
    **/
    static java.util.concurrent.CompletionStage<com.zeroc.Ice.OutputStream> _iceD_getGroupHistory(ChatService obj, final com.zeroc.IceInternal.Incoming inS, com.zeroc.Ice.Current current)
        throws com.zeroc.Ice.UserException
    {
        com.zeroc.Ice.Object._iceCheckMode(null, current.mode);
        com.zeroc.Ice.InputStream istr = inS.startReadParams();
        String iceP_groupName;
        iceP_groupName = istr.readString();
        inS.endReadParams();
        MessageInfo[] ret = obj.getGroupHistory(iceP_groupName, current);
        com.zeroc.Ice.OutputStream ostr = inS.startWriteParams();
        MessageSeqHelper.write(ostr, ret);
        inS.endWriteParams(ostr);
        return inS.setResult(ostr);
    }

    /**
     * @hidden
     * @param obj -
     * @param inS -
     * @param current -
     * @return -
     * @throws com.zeroc.Ice.UserException -
    **/
    static java.util.concurrent.CompletionStage<com.zeroc.Ice.OutputStream> _iceD_createGroup(ChatService obj, final com.zeroc.IceInternal.Incoming inS, com.zeroc.Ice.Current current)
        throws com.zeroc.Ice.UserException
    {
        com.zeroc.Ice.Object._iceCheckMode(null, current.mode);
        com.zeroc.Ice.InputStream istr = inS.startReadParams();
        String iceP_groupName;
        String iceP_creator;
        String[] iceP_members;
        iceP_groupName = istr.readString();
        iceP_creator = istr.readString();
        iceP_members = istr.readStringSeq();
        inS.endReadParams();
        boolean ret = obj.createGroup(iceP_groupName, iceP_creator, iceP_members, current);
        com.zeroc.Ice.OutputStream ostr = inS.startWriteParams();
        ostr.writeBool(ret);
        inS.endWriteParams(ostr);
        return inS.setResult(ostr);
    }

    /**
     * @hidden
     * @param obj -
     * @param inS -
     * @param current -
     * @return -
     * @throws com.zeroc.Ice.UserException -
    **/
    static java.util.concurrent.CompletionStage<com.zeroc.Ice.OutputStream> _iceD_joinGroup(ChatService obj, final com.zeroc.IceInternal.Incoming inS, com.zeroc.Ice.Current current)
        throws com.zeroc.Ice.UserException
    {
        com.zeroc.Ice.Object._iceCheckMode(null, current.mode);
        com.zeroc.Ice.InputStream istr = inS.startReadParams();
        String iceP_username;
        String iceP_groupName;
        iceP_username = istr.readString();
        iceP_groupName = istr.readString();
        inS.endReadParams();
        boolean ret = obj.joinGroup(iceP_username, iceP_groupName, current);
        com.zeroc.Ice.OutputStream ostr = inS.startWriteParams();
        ostr.writeBool(ret);
        inS.endWriteParams(ostr);
        return inS.setResult(ostr);
    }

    /**
     * @hidden
     * @param obj -
     * @param inS -
     * @param current -
     * @return -
     * @throws com.zeroc.Ice.UserException -
    **/
    static java.util.concurrent.CompletionStage<com.zeroc.Ice.OutputStream> _iceD_leaveGroup(ChatService obj, final com.zeroc.IceInternal.Incoming inS, com.zeroc.Ice.Current current)
        throws com.zeroc.Ice.UserException
    {
        com.zeroc.Ice.Object._iceCheckMode(null, current.mode);
        com.zeroc.Ice.InputStream istr = inS.startReadParams();
        String iceP_username;
        String iceP_groupName;
        iceP_username = istr.readString();
        iceP_groupName = istr.readString();
        inS.endReadParams();
        boolean ret = obj.leaveGroup(iceP_username, iceP_groupName, current);
        com.zeroc.Ice.OutputStream ostr = inS.startWriteParams();
        ostr.writeBool(ret);
        inS.endWriteParams(ostr);
        return inS.setResult(ostr);
    }

    /**
     * @hidden
     * @param obj -
     * @param inS -
     * @param current -
     * @return -
     * @throws com.zeroc.Ice.UserException -
    **/
    static java.util.concurrent.CompletionStage<com.zeroc.Ice.OutputStream> _iceD_getUserGroups(ChatService obj, final com.zeroc.IceInternal.Incoming inS, com.zeroc.Ice.Current current)
        throws com.zeroc.Ice.UserException
    {
        com.zeroc.Ice.Object._iceCheckMode(null, current.mode);
        com.zeroc.Ice.InputStream istr = inS.startReadParams();
        String iceP_username;
        iceP_username = istr.readString();
        inS.endReadParams();
        GroupInfo[] ret = obj.getUserGroups(iceP_username, current);
        com.zeroc.Ice.OutputStream ostr = inS.startWriteParams();
        GroupSeqHelper.write(ostr, ret);
        inS.endWriteParams(ostr);
        return inS.setResult(ostr);
    }

    /**
     * @hidden
     * @param obj -
     * @param inS -
     * @param current -
     * @return -
     * @throws com.zeroc.Ice.UserException -
    **/
    static java.util.concurrent.CompletionStage<com.zeroc.Ice.OutputStream> _iceD_getGroupMembers(ChatService obj, final com.zeroc.IceInternal.Incoming inS, com.zeroc.Ice.Current current)
        throws com.zeroc.Ice.UserException
    {
        com.zeroc.Ice.Object._iceCheckMode(null, current.mode);
        com.zeroc.Ice.InputStream istr = inS.startReadParams();
        String iceP_groupName;
        iceP_groupName = istr.readString();
        inS.endReadParams();
        String[] ret = obj.getGroupMembers(iceP_groupName, current);
        com.zeroc.Ice.OutputStream ostr = inS.startWriteParams();
        ostr.writeStringSeq(ret);
        inS.endWriteParams(ostr);
        return inS.setResult(ostr);
    }

    /**
     * @hidden
     * @param obj -
     * @param inS -
     * @param current -
     * @return -
     * @throws com.zeroc.Ice.UserException -
    **/
    static java.util.concurrent.CompletionStage<com.zeroc.Ice.OutputStream> _iceD_sendAudio(ChatService obj, final com.zeroc.IceInternal.Incoming inS, com.zeroc.Ice.Current current)
        throws com.zeroc.Ice.UserException
    {
        com.zeroc.Ice.Object._iceCheckMode(null, current.mode);
        com.zeroc.Ice.InputStream istr = inS.startReadParams();
        String iceP_from;
        String iceP_to;
        String iceP_audioId;
        int iceP_size;
        int iceP_duration;
        iceP_from = istr.readString();
        iceP_to = istr.readString();
        iceP_audioId = istr.readString();
        iceP_size = istr.readInt();
        iceP_duration = istr.readInt();
        inS.endReadParams();
        boolean ret = obj.sendAudio(iceP_from, iceP_to, iceP_audioId, iceP_size, iceP_duration, current);
        com.zeroc.Ice.OutputStream ostr = inS.startWriteParams();
        ostr.writeBool(ret);
        inS.endWriteParams(ostr);
        return inS.setResult(ostr);
    }

    /**
     * @hidden
     * @param obj -
     * @param inS -
     * @param current -
     * @return -
     * @throws com.zeroc.Ice.UserException -
    **/
    static java.util.concurrent.CompletionStage<com.zeroc.Ice.OutputStream> _iceD_sendGroupAudio(ChatService obj, final com.zeroc.IceInternal.Incoming inS, com.zeroc.Ice.Current current)
        throws com.zeroc.Ice.UserException
    {
        com.zeroc.Ice.Object._iceCheckMode(null, current.mode);
        com.zeroc.Ice.InputStream istr = inS.startReadParams();
        String iceP_from;
        String iceP_groupName;
        String iceP_audioId;
        int iceP_size;
        int iceP_duration;
        iceP_from = istr.readString();
        iceP_groupName = istr.readString();
        iceP_audioId = istr.readString();
        iceP_size = istr.readInt();
        iceP_duration = istr.readInt();
        inS.endReadParams();
        boolean ret = obj.sendGroupAudio(iceP_from, iceP_groupName, iceP_audioId, iceP_size, iceP_duration, current);
        com.zeroc.Ice.OutputStream ostr = inS.startWriteParams();
        ostr.writeBool(ret);
        inS.endWriteParams(ostr);
        return inS.setResult(ostr);
    }

    /**
     * @hidden
     * @param obj -
     * @param inS -
     * @param current -
     * @return -
     * @throws com.zeroc.Ice.UserException -
    **/
    static java.util.concurrent.CompletionStage<com.zeroc.Ice.OutputStream> _iceD_getPrivateAudioHistory(ChatService obj, final com.zeroc.IceInternal.Incoming inS, com.zeroc.Ice.Current current)
        throws com.zeroc.Ice.UserException
    {
        com.zeroc.Ice.Object._iceCheckMode(null, current.mode);
        com.zeroc.Ice.InputStream istr = inS.startReadParams();
        String iceP_username;
        String iceP_target;
        iceP_username = istr.readString();
        iceP_target = istr.readString();
        inS.endReadParams();
        AudioInfo[] ret = obj.getPrivateAudioHistory(iceP_username, iceP_target, current);
        com.zeroc.Ice.OutputStream ostr = inS.startWriteParams();
        AudioSeqHelper.write(ostr, ret);
        inS.endWriteParams(ostr);
        return inS.setResult(ostr);
    }

    /**
     * @hidden
     * @param obj -
     * @param inS -
     * @param current -
     * @return -
     * @throws com.zeroc.Ice.UserException -
    **/
    static java.util.concurrent.CompletionStage<com.zeroc.Ice.OutputStream> _iceD_getGroupAudioHistory(ChatService obj, final com.zeroc.IceInternal.Incoming inS, com.zeroc.Ice.Current current)
        throws com.zeroc.Ice.UserException
    {
        com.zeroc.Ice.Object._iceCheckMode(null, current.mode);
        com.zeroc.Ice.InputStream istr = inS.startReadParams();
        String iceP_groupName;
        iceP_groupName = istr.readString();
        inS.endReadParams();
        AudioInfo[] ret = obj.getGroupAudioHistory(iceP_groupName, current);
        com.zeroc.Ice.OutputStream ostr = inS.startWriteParams();
        AudioSeqHelper.write(ostr, ret);
        inS.endWriteParams(ostr);
        return inS.setResult(ostr);
    }

    /**
     * @hidden
     * @param obj -
     * @param inS -
     * @param current -
     * @return -
     * @throws com.zeroc.Ice.UserException -
    **/
    static java.util.concurrent.CompletionStage<com.zeroc.Ice.OutputStream> _iceD_getOnlineUsers(ChatService obj, final com.zeroc.IceInternal.Incoming inS, com.zeroc.Ice.Current current)
        throws com.zeroc.Ice.UserException
    {
        com.zeroc.Ice.Object._iceCheckMode(null, current.mode);
        inS.readEmptyParams();
        String[] ret = obj.getOnlineUsers(current);
        com.zeroc.Ice.OutputStream ostr = inS.startWriteParams();
        ostr.writeStringSeq(ret);
        inS.endWriteParams(ostr);
        return inS.setResult(ostr);
    }

    /**
     * @hidden
     * @param obj -
     * @param inS -
     * @param current -
     * @return -
     * @throws com.zeroc.Ice.UserException -
    **/
    static java.util.concurrent.CompletionStage<com.zeroc.Ice.OutputStream> _iceD_getAllUsers(ChatService obj, final com.zeroc.IceInternal.Incoming inS, com.zeroc.Ice.Current current)
        throws com.zeroc.Ice.UserException
    {
        com.zeroc.Ice.Object._iceCheckMode(null, current.mode);
        inS.readEmptyParams();
        UserInfo[] ret = obj.getAllUsers(current);
        com.zeroc.Ice.OutputStream ostr = inS.startWriteParams();
        UserSeqHelper.write(ostr, ret);
        inS.endWriteParams(ostr);
        return inS.setResult(ostr);
    }

    /**
     * @hidden
     * @param obj -
     * @param inS -
     * @param current -
     * @return -
     * @throws com.zeroc.Ice.UserException -
    **/
    static java.util.concurrent.CompletionStage<com.zeroc.Ice.OutputStream> _iceD_isUserOnline(ChatService obj, final com.zeroc.IceInternal.Incoming inS, com.zeroc.Ice.Current current)
        throws com.zeroc.Ice.UserException
    {
        com.zeroc.Ice.Object._iceCheckMode(null, current.mode);
        com.zeroc.Ice.InputStream istr = inS.startReadParams();
        String iceP_username;
        iceP_username = istr.readString();
        inS.endReadParams();
        boolean ret = obj.isUserOnline(iceP_username, current);
        com.zeroc.Ice.OutputStream ostr = inS.startWriteParams();
        ostr.writeBool(ret);
        inS.endWriteParams(ostr);
        return inS.setResult(ostr);
    }

    /**
     * @hidden
     * @param obj -
     * @param inS -
     * @param current -
     * @return -
     * @throws com.zeroc.Ice.UserException -
    **/
    static java.util.concurrent.CompletionStage<com.zeroc.Ice.OutputStream> _iceD_getServerStatus(ChatService obj, final com.zeroc.IceInternal.Incoming inS, com.zeroc.Ice.Current current)
        throws com.zeroc.Ice.UserException
    {
        com.zeroc.Ice.Object._iceCheckMode(com.zeroc.Ice.OperationMode.Idempotent, current.mode);
        inS.readEmptyParams();
        String ret = obj.getServerStatus(current);
        com.zeroc.Ice.OutputStream ostr = inS.startWriteParams();
        ostr.writeString(ret);
        inS.endWriteParams(ostr);
        return inS.setResult(ostr);
    }

    /** @hidden */
    final static String[] _iceOps =
    {
        "createGroup",
        "getAllUsers",
        "getGroupAudioHistory",
        "getGroupHistory",
        "getGroupMembers",
        "getOnlineUsers",
        "getPrivateAudioHistory",
        "getPrivateHistory",
        "getServerStatus",
        "getUserGroups",
        "ice_id",
        "ice_ids",
        "ice_isA",
        "ice_ping",
        "isUserOnline",
        "joinGroup",
        "leaveGroup",
        "login",
        "logout",
        "sendAudio",
        "sendGroupAudio",
        "sendGroupMessage",
        "sendMessage"
    };

    /** @hidden */
    @Override
    default java.util.concurrent.CompletionStage<com.zeroc.Ice.OutputStream> _iceDispatch(com.zeroc.IceInternal.Incoming in, com.zeroc.Ice.Current current)
        throws com.zeroc.Ice.UserException
    {
        int pos = java.util.Arrays.binarySearch(_iceOps, current.operation);
        if(pos < 0)
        {
            throw new com.zeroc.Ice.OperationNotExistException(current.id, current.facet, current.operation);
        }

        switch(pos)
        {
            case 0:
            {
                return _iceD_createGroup(this, in, current);
            }
            case 1:
            {
                return _iceD_getAllUsers(this, in, current);
            }
            case 2:
            {
                return _iceD_getGroupAudioHistory(this, in, current);
            }
            case 3:
            {
                return _iceD_getGroupHistory(this, in, current);
            }
            case 4:
            {
                return _iceD_getGroupMembers(this, in, current);
            }
            case 5:
            {
                return _iceD_getOnlineUsers(this, in, current);
            }
            case 6:
            {
                return _iceD_getPrivateAudioHistory(this, in, current);
            }
            case 7:
            {
                return _iceD_getPrivateHistory(this, in, current);
            }
            case 8:
            {
                return _iceD_getServerStatus(this, in, current);
            }
            case 9:
            {
                return _iceD_getUserGroups(this, in, current);
            }
            case 10:
            {
                return com.zeroc.Ice.Object._iceD_ice_id(this, in, current);
            }
            case 11:
            {
                return com.zeroc.Ice.Object._iceD_ice_ids(this, in, current);
            }
            case 12:
            {
                return com.zeroc.Ice.Object._iceD_ice_isA(this, in, current);
            }
            case 13:
            {
                return com.zeroc.Ice.Object._iceD_ice_ping(this, in, current);
            }
            case 14:
            {
                return _iceD_isUserOnline(this, in, current);
            }
            case 15:
            {
                return _iceD_joinGroup(this, in, current);
            }
            case 16:
            {
                return _iceD_leaveGroup(this, in, current);
            }
            case 17:
            {
                return _iceD_login(this, in, current);
            }
            case 18:
            {
                return _iceD_logout(this, in, current);
            }
            case 19:
            {
                return _iceD_sendAudio(this, in, current);
            }
            case 20:
            {
                return _iceD_sendGroupAudio(this, in, current);
            }
            case 21:
            {
                return _iceD_sendGroupMessage(this, in, current);
            }
            case 22:
            {
                return _iceD_sendMessage(this, in, current);
            }
        }

        assert(false);
        throw new com.zeroc.Ice.OperationNotExistException(current.id, current.facet, current.operation);
    }
}
