//
// Copyright (c) ZeroC, Inc. All rights reserved.
//
//
// Ice version 3.7.10
//
// <auto-generated>
//
// Generated from file `chat.ice'
//
// Warning: do not edit this file.
//
// </auto-generated>
//

package chat;

/**
 * Helper class for marshaling/unmarshaling GroupSeq.
 **/
public final class GroupSeqHelper
{
    public static void write(com.zeroc.Ice.OutputStream ostr, GroupInfo[] v)
    {
        if(v == null)
        {
            ostr.writeSize(0);
        }
        else
        {
            ostr.writeSize(v.length);
            for(int i0 = 0; i0 < v.length; i0++)
            {
                GroupInfo.ice_write(ostr, v[i0]);
            }
        }
    }

    public static GroupInfo[] read(com.zeroc.Ice.InputStream istr)
    {
        final GroupInfo[] v;
        final int len0 = istr.readAndCheckSeqSize(3);
        v = new GroupInfo[len0];
        for(int i0 = 0; i0 < len0; i0++)
        {
            v[i0] = GroupInfo.ice_read(istr);
        }
        return v;
    }

    public static void write(com.zeroc.Ice.OutputStream ostr, int tag, java.util.Optional<GroupInfo[]> v)
    {
        if(v != null && v.isPresent())
        {
            write(ostr, tag, v.get());
        }
    }

    public static void write(com.zeroc.Ice.OutputStream ostr, int tag, GroupInfo[] v)
    {
        if(ostr.writeOptional(tag, com.zeroc.Ice.OptionalFormat.FSize))
        {
            int pos = ostr.startSize();
            GroupSeqHelper.write(ostr, v);
            ostr.endSize(pos);
        }
    }

    public static java.util.Optional<GroupInfo[]> read(com.zeroc.Ice.InputStream istr, int tag)
    {
        if(istr.readOptional(tag, com.zeroc.Ice.OptionalFormat.FSize))
        {
            istr.skip(4);
            GroupInfo[] v;
            v = GroupSeqHelper.read(istr);
            return java.util.Optional.of(v);
        }
        else
        {
            return java.util.Optional.empty();
        }
    }
}
