//
// Copyright (c) ZeroC, Inc. All rights reserved.
//
//
// Ice version 3.7.10
//
// <auto-generated>
//
// Generated from file `chat.ice'
//
// Warning: do not edit this file.
//
// </auto-generated>
//

package chat;

public class MessageInfo implements java.lang.Cloneable,
                                    java.io.Serializable
{
    public String id;

    public String from;

    public String to;

    public String content;

    public long timestamp;

    public boolean isGroup;

    public MessageInfo()
    {
        this.id = "";
        this.from = "";
        this.to = "";
        this.content = "";
    }

    public MessageInfo(String id, String from, String to, String content, long timestamp, boolean isGroup)
    {
        this.id = id;
        this.from = from;
        this.to = to;
        this.content = content;
        this.timestamp = timestamp;
        this.isGroup = isGroup;
    }

    public boolean equals(java.lang.Object rhs)
    {
        if(this == rhs)
        {
            return true;
        }
        MessageInfo r = null;
        if(rhs instanceof MessageInfo)
        {
            r = (MessageInfo)rhs;
        }

        if(r != null)
        {
            if(this.id != r.id)
            {
                if(this.id == null || r.id == null || !this.id.equals(r.id))
                {
                    return false;
                }
            }
            if(this.from != r.from)
            {
                if(this.from == null || r.from == null || !this.from.equals(r.from))
                {
                    return false;
                }
            }
            if(this.to != r.to)
            {
                if(this.to == null || r.to == null || !this.to.equals(r.to))
                {
                    return false;
                }
            }
            if(this.content != r.content)
            {
                if(this.content == null || r.content == null || !this.content.equals(r.content))
                {
                    return false;
                }
            }
            if(this.timestamp != r.timestamp)
            {
                return false;
            }
            if(this.isGroup != r.isGroup)
            {
                return false;
            }

            return true;
        }

        return false;
    }

    public int hashCode()
    {
        int h_ = 5381;
        h_ = com.zeroc.IceInternal.HashUtil.hashAdd(h_, "::chat::MessageInfo");
        h_ = com.zeroc.IceInternal.HashUtil.hashAdd(h_, id);
        h_ = com.zeroc.IceInternal.HashUtil.hashAdd(h_, from);
        h_ = com.zeroc.IceInternal.HashUtil.hashAdd(h_, to);
        h_ = com.zeroc.IceInternal.HashUtil.hashAdd(h_, content);
        h_ = com.zeroc.IceInternal.HashUtil.hashAdd(h_, timestamp);
        h_ = com.zeroc.IceInternal.HashUtil.hashAdd(h_, isGroup);
        return h_;
    }

    public MessageInfo clone()
    {
        MessageInfo c = null;
        try
        {
            c = (MessageInfo)super.clone();
        }
        catch(CloneNotSupportedException ex)
        {
            assert false; // impossible
        }
        return c;
    }

    public void ice_writeMembers(com.zeroc.Ice.OutputStream ostr)
    {
        ostr.writeString(this.id);
        ostr.writeString(this.from);
        ostr.writeString(this.to);
        ostr.writeString(this.content);
        ostr.writeLong(this.timestamp);
        ostr.writeBool(this.isGroup);
    }

    public void ice_readMembers(com.zeroc.Ice.InputStream istr)
    {
        this.id = istr.readString();
        this.from = istr.readString();
        this.to = istr.readString();
        this.content = istr.readString();
        this.timestamp = istr.readLong();
        this.isGroup = istr.readBool();
    }

    static public void ice_write(com.zeroc.Ice.OutputStream ostr, MessageInfo v)
    {
        if(v == null)
        {
            _nullMarshalValue.ice_writeMembers(ostr);
        }
        else
        {
            v.ice_writeMembers(ostr);
        }
    }

    static public MessageInfo ice_read(com.zeroc.Ice.InputStream istr)
    {
        MessageInfo v = new MessageInfo();
        v.ice_readMembers(istr);
        return v;
    }

    static public void ice_write(com.zeroc.Ice.OutputStream ostr, int tag, java.util.Optional<MessageInfo> v)
    {
        if(v != null && v.isPresent())
        {
            ice_write(ostr, tag, v.get());
        }
    }

    static public void ice_write(com.zeroc.Ice.OutputStream ostr, int tag, MessageInfo v)
    {
        if(ostr.writeOptional(tag, com.zeroc.Ice.OptionalFormat.FSize))
        {
            int pos = ostr.startSize();
            ice_write(ostr, v);
            ostr.endSize(pos);
        }
    }

    static public java.util.Optional<MessageInfo> ice_read(com.zeroc.Ice.InputStream istr, int tag)
    {
        if(istr.readOptional(tag, com.zeroc.Ice.OptionalFormat.FSize))
        {
            istr.skip(4);
            return java.util.Optional.of(MessageInfo.ice_read(istr));
        }
        else
        {
            return java.util.Optional.empty();
        }
    }

    private static final MessageInfo _nullMarshalValue = new MessageInfo();

    /** @hidden */
    public static final long serialVersionUID = -1568868558L;
}
