//
// Copyright (c) ZeroC, Inc. All rights reserved.
//
//
// Ice version 3.7.10
//
// <auto-generated>
//
// Generated from file `chat.ice'
//
// Warning: do not edit this file.
//
// </auto-generated>
//

package chat;

/**
 * Helper class for marshaling/unmarshaling UserSeq.
 **/
public final class UserSeqHelper
{
    public static void write(com.zeroc.Ice.OutputStream ostr, UserInfo[] v)
    {
        if(v == null)
        {
            ostr.writeSize(0);
        }
        else
        {
            ostr.writeSize(v.length);
            for(int i0 = 0; i0 < v.length; i0++)
            {
                UserInfo.ice_write(ostr, v[i0]);
            }
        }
    }

    public static UserInfo[] read(com.zeroc.Ice.InputStream istr)
    {
        final UserInfo[] v;
        final int len0 = istr.readAndCheckSeqSize(2);
        v = new UserInfo[len0];
        for(int i0 = 0; i0 < len0; i0++)
        {
            v[i0] = UserInfo.ice_read(istr);
        }
        return v;
    }

    public static void write(com.zeroc.Ice.OutputStream ostr, int tag, java.util.Optional<UserInfo[]> v)
    {
        if(v != null && v.isPresent())
        {
            write(ostr, tag, v.get());
        }
    }

    public static void write(com.zeroc.Ice.OutputStream ostr, int tag, UserInfo[] v)
    {
        if(ostr.writeOptional(tag, com.zeroc.Ice.OptionalFormat.FSize))
        {
            int pos = ostr.startSize();
            UserSeqHelper.write(ostr, v);
            ostr.endSize(pos);
        }
    }

    public static java.util.Optional<UserInfo[]> read(com.zeroc.Ice.InputStream istr, int tag)
    {
        if(istr.readOptional(tag, com.zeroc.Ice.OptionalFormat.FSize))
        {
            istr.skip(4);
            UserInfo[] v;
            v = UserSeqHelper.read(istr);
            return java.util.Optional.of(v);
        }
        else
        {
            return java.util.Optional.empty();
        }
    }
}
