//
// Copyright (c) ZeroC, Inc. All rights reserved.
//
//
// Ice version 3.7.10
//
// <auto-generated>
//
// Generated from file `chat.ice'
//
// Warning: do not edit this file.
//
// </auto-generated>
//

/* eslint-disable */
/* jshint ignore: start */

(function(module, require, exports)
{
    const Ice = require("ice").Ice;
    const _ModuleRegistry = Ice._ModuleRegistry;
    const Slice = Ice.Slice;

    let chat = _ModuleRegistry.module("chat");

    Slice.defineSequence(chat, "StringSeqHelper", "Ice.StringHelper", false);

    chat.MessageInfo = class
    {
        constructor(id = "", from = "", to = "", content = "", timestamp = new Ice.Long(0, 0), isGroup = false)
        {
            this.id = id;
            this.from = from;
            this.to = to;
            this.content = content;
            this.timestamp = timestamp;
            this.isGroup = isGroup;
        }

        _write(ostr)
        {
            ostr.writeString(this.id);
            ostr.writeString(this.from);
            ostr.writeString(this.to);
            ostr.writeString(this.content);
            ostr.writeLong(this.timestamp);
            ostr.writeBool(this.isGroup);
        }

        _read(istr)
        {
            this.id = istr.readString();
            this.from = istr.readString();
            this.to = istr.readString();
            this.content = istr.readString();
            this.timestamp = istr.readLong();
            this.isGroup = istr.readBool();
        }

        static get minWireSize()
        {
            return  13;
        }
    };

    Slice.defineStruct(chat.MessageInfo, true, true);

    chat.AudioInfo = class
    {
        constructor(id = "", from = "", to = "", timestamp = new Ice.Long(0, 0), isGroup = false, duration = 0, size = 0)
        {
            this.id = id;
            this.from = from;
            this.to = to;
            this.timestamp = timestamp;
            this.isGroup = isGroup;
            this.duration = duration;
            this.size = size;
        }

        _write(ostr)
        {
            ostr.writeString(this.id);
            ostr.writeString(this.from);
            ostr.writeString(this.to);
            ostr.writeLong(this.timestamp);
            ostr.writeBool(this.isGroup);
            ostr.writeInt(this.duration);
            ostr.writeInt(this.size);
        }

        _read(istr)
        {
            this.id = istr.readString();
            this.from = istr.readString();
            this.to = istr.readString();
            this.timestamp = istr.readLong();
            this.isGroup = istr.readBool();
            this.duration = istr.readInt();
            this.size = istr.readInt();
        }

        static get minWireSize()
        {
            return  20;
        }
    };

    Slice.defineStruct(chat.AudioInfo, true, true);

    Slice.defineSequence(chat, "MessageSeqHelper", "chat.MessageInfo", false);

    Slice.defineSequence(chat, "AudioSeqHelper", "chat.AudioInfo", false);

    chat.UserInfo = class
    {
        constructor(name = "", online = false)
        {
            this.name = name;
            this.online = online;
        }

        _write(ostr)
        {
            ostr.writeString(this.name);
            ostr.writeBool(this.online);
        }

        _read(istr)
        {
            this.name = istr.readString();
            this.online = istr.readBool();
        }

        static get minWireSize()
        {
            return  2;
        }
    };

    Slice.defineStruct(chat.UserInfo, true, true);

    Slice.defineSequence(chat, "UserSeqHelper", "chat.UserInfo", false);

    chat.GroupInfo = class
    {
        constructor(name = "", creator = "", members = null)
        {
            this.name = name;
            this.creator = creator;
            this.members = members;
        }

        _write(ostr)
        {
            ostr.writeString(this.name);
            ostr.writeString(this.creator);
            chat.StringSeqHelper.write(ostr, this.members);
        }

        _read(istr)
        {
            this.name = istr.readString();
            this.creator = istr.readString();
            this.members = chat.StringSeqHelper.read(istr);
        }

        static get minWireSize()
        {
            return  3;
        }
    };

    Slice.defineStruct(chat.GroupInfo, true, true);

    Slice.defineSequence(chat, "GroupSeqHelper", "chat.GroupInfo", false);

    chat.UserException = class extends Ice.UserException
    {
        constructor(message = "", _cause = "")
        {
            super(_cause);
            this.message = message;
        }

        static get _parent()
        {
            return Ice.UserException;
        }

        static get _id()
        {
            return "::chat::UserException";
        }

        _mostDerivedType()
        {
            return chat.UserException;
        }

        _writeMemberImpl(ostr)
        {
            ostr.writeString(this.message);
        }

        _readMemberImpl(istr)
        {
            this.message = istr.readString();
        }
    };

    const iceC_chat_ChatService_ids = [
        "::Ice::Object",
        "::chat::ChatService"
    ];

    chat.ChatService = class extends Ice.Object
    {
    };

    chat.ChatServicePrx = class extends Ice.ObjectPrx
    {
    };

    Slice.defineOperations(chat.ChatService, chat.ChatServicePrx, iceC_chat_ChatService_ids, 1,
    {
        "login": [, , , , [1], [[7]], ,
        [
            chat.UserException
        ], , ],
        "logout": [, , , , [1], [[7]], ,
        [
            chat.UserException
        ], , ],
        "sendMessage": [, , , , [1], [[7], [7], [7]], ,
        [
            chat.UserException
        ], , ],
        "getPrivateHistory": [, , , , ["chat.MessageSeqHelper"], [[7], [7]], ,
        [
            chat.UserException
        ], , ],
        "sendGroupMessage": [, , , , [1], [[7], [7], [7]], ,
        [
            chat.UserException
        ], , ],
        "getGroupHistory": [, , , , ["chat.MessageSeqHelper"], [[7]], ,
        [
            chat.UserException
        ], , ],
        "createGroup": [, , , , [1], [[7], [7], ["chat.StringSeqHelper"]], ,
        [
            chat.UserException
        ], , ],
        "joinGroup": [, , , , [1], [[7], [7]], ,
        [
            chat.UserException
        ], , ],
        "leaveGroup": [, , , , [1], [[7], [7]], ,
        [
            chat.UserException
        ], , ],
        "getUserGroups": [, , , , ["chat.GroupSeqHelper"], [[7]], ,
        [
            chat.UserException
        ], , ],
        "getGroupMembers": [, , , , ["chat.StringSeqHelper"], [[7]], ,
        [
            chat.UserException
        ], , ],
        "sendAudio": [, , , , [1], [[7], [7], [7], [3], [3]], ,
        [
            chat.UserException
        ], , ],
        "sendGroupAudio": [, , , , [1], [[7], [7], [7], [3], [3]], ,
        [
            chat.UserException
        ], , ],
        "getPrivateAudioHistory": [, , , , ["chat.AudioSeqHelper"], [[7], [7]], ,
        [
            chat.UserException
        ], , ],
        "getGroupAudioHistory": [, , , , ["chat.AudioSeqHelper"], [[7]], ,
        [
            chat.UserException
        ], , ],
        "getOnlineUsers": [, , , , ["chat.StringSeqHelper"], , ,
        [
            chat.UserException
        ], , ],
        "getAllUsers": [, , , , ["chat.UserSeqHelper"], , ,
        [
            chat.UserException
        ], , ],
        "isUserOnline": [, , , , [1], [[7]], ,
        [
            chat.UserException
        ], , ],
        "getServerStatus": [, 2, 2, , [7], , ,
        [
            chat.UserException
        ], , ]
    });
    exports.chat = chat;
}
(typeof(global) !== "undefined" && typeof(global.process) !== "undefined" ? module : undefined,
 typeof(global) !== "undefined" && typeof(global.process) !== "undefined" ? require :
 (typeof WorkerGlobalScope !== "undefined" && self instanceof WorkerGlobalScope) ? self.Ice._require : window.Ice._require,
 typeof(global) !== "undefined" && typeof(global.process) !== "undefined" ? exports :
 (typeof WorkerGlobalScope !== "undefined" && self instanceof WorkerGlobalScope) ? self : window));
